INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('ramon', 'serrano', 'ramon@ramon.com','c/desconocida',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('dani', 'maci', 'dani@maci.com','c/getafe',9846463,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Hugo', 'Santana', 'hugo@santana.com','c/mostoles',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Cristian', 'velazquez', 'cristian@gmail.com','Calle Alea',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Jorge', 'Universidad', 'Jorge@gmail.com','c/salmueros',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('alicia', 'rodriguez', 'alicia@gmail.com','c/murcia',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('aberto', 'serrano', 'ramon@ramon.com','c/miami',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Michael', 'Gallego', 'mic@gmail.com','c/frackfurt',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Patxi', 'lopez', 'patxi@gmail.com','c/berlin',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('cristina', 'garcia', 'cristina@gmail.com','c/miraflor',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('ana', 'serrano', 'aba@gmail.com','c/conde',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('maria', 'serrano', 'maria@gmail.com','c/zorron',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('antonia', 'serrano', 'antonia@gmail.com','c/mira que si voy',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('fidel', 'castro', 'fidel@gmail.com','c/genocida',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Santiago ', 'Barnabeu', 'satiago@gmail.com','c/estadio',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Cristiano', 'Ronaldo', 'cristianao@gmail.com','c/abdominal',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Raul', 'Blanco', 'raul@gmail.com','c/burbuja',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Florentino', 'Perez', 'titofloren@gmail.com','c/ricachoes',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Valentino', 'Rossi', 'vale46@gmail.com','c/italia',12345,'','');
INSERT INTO User (first_Name,last_Name,email,direccion,cp,password,foto) VALUES ('Marc', 'Marquez', 'marc@gmail.com','c/honda',12345,'','');
